### ISSUE TITLE
(n_updates + 2) ** (-alpha)

### ISSUE THREAD

**Issue by Anaphory** [PhyloStar/CogDetect#19]
The code in `online_pmi` calculates `eta`, which is something like the momentum for updating PMI scores, as

                eta = (n_updates + 2) ** (-alpha)
Where does that formula come from in general, and why are 2 and -0.75 good magical values in there?

I would have expected iterations to be quite independent of each other, so the fact that eta contains some memory of how many updates have happened in previous iterations – instead of a flat exponential decay, `eta = alpha ** n_updates` or something – surprises me.

**Comment by erathorn** [comment]
The formula comes from:
https://cs.stanford.edu/~pliang/papers/online-naacl2009.pdf
The 2 is not an estimated parameter but rather an integral part. The 0.75 worked best in a couple of experiments we did. The respective paper is currently under review.

**Comment by Anaphory** [comment]
Cool! It's interesting, it makes splitting out the core iterative improvement code into a separate function which I can call from elsewhere more challenging, because I need to think about how to pass those parameters around.

**Comment by erathorn** [comment]
You may want to have a look at the PHMM_code branch. In the file [`Wrapper_Public.py`](https://github.com/PhyloStar/CogDetect/blob/PHMM_Code/PairHiddenMarkovModel/Wrapper_Public.py) there is a function called ``merge``, which does exactly this update step in terms of ``numpy`` multiplications.

**Comment by Anaphory** [comment]
Ah. What I meant is:

If I want to write an `iteration` function containing the

        for idx in range(0, len(word_pairs), min_batch):
loop, I need to seriously think about how to best structure its signature, because it probably needs to pass several arguments passed to it and returned for the next iteration, so it might be useful to not write it as a single function but as a class that keeps those objects persistent.
